#ifndef MODFEM_HEATUI_0_METADATA_HPP
#define MODFEM_HEATUI_0_METADATA_HPP

// This file has been autogenerated by 'cutehmi.metadata' Qbs module.

#define MODFEM_HEATUI_NAME "ModFEM.HeatUI.0"
#define MODFEM_HEATUI_CUTEHMI_TYPE "extension"
#define MODFEM_HEATUI_FRIENDLY_NAME "Heat User Interface"
#define MODFEM_HEATUI_VENDOR "ModFEM"
#define MODFEM_HEATUI_DOMAIN "modfem.agh.edu.pl"
#define MODFEM_HEATUI_VERSION "0.0.0"
#define MODFEM_HEATUI_MAJOR 0
#define MODFEM_HEATUI_MINOR 0
#define MODFEM_HEATUI_MICRO 0

#ifdef MODFEM_HEATUI_BUILD
  #define MODFEM_HEATUI_0_0
#endif

#ifndef MODFEM_HEATUI_0_CURRENT 
  #define MODFEM_HEATUI_0_CURRENT 0
#endif

#endif
