#ifndef MODFEM_VIEW3D_1_METADATA_HPP
#define MODFEM_VIEW3D_1_METADATA_HPP

// This file has been autogenerated by 'cutehmi.metadata' Qbs module.

#define MODFEM_VIEW3D_NAME "ModFEM.View3d.1"
#define MODFEM_VIEW3D_CUTEHMI_TYPE "extension"
#define MODFEM_VIEW3D_FRIENDLY_NAME "View 3d"
#define MODFEM_VIEW3D_VENDOR "CuteHMI"
#define MODFEM_VIEW3D_DOMAIN "cutehmi.kde.org"
#define MODFEM_VIEW3D_VERSION "1.0.0"
#define MODFEM_VIEW3D_MAJOR 1
#define MODFEM_VIEW3D_MINOR 0
#define MODFEM_VIEW3D_MICRO 0

#ifdef MODFEM_VIEW3D_BUILD
  #define MODFEM_VIEW3D_1_0
#endif

#ifndef MODFEM_VIEW3D_1_CURRENT 
  #define MODFEM_VIEW3D_1_CURRENT 0
#endif

#endif
