#ifndef MODFEM_QTHEAT_0_METADATA_HPP
#define MODFEM_QTHEAT_0_METADATA_HPP

// This file has been autogenerated by 'cutehmi.metadata' Qbs module.

#define MODFEM_QTHEAT_NAME "ModFEM.QtHeat.0"
#define MODFEM_QTHEAT_CUTEHMI_TYPE "extension"
#define MODFEM_QTHEAT_FRIENDLY_NAME "Heat Qt interface"
#define MODFEM_QTHEAT_VENDOR "ModFEM"
#define MODFEM_QTHEAT_DOMAIN "modfem.agh.edu.pl"
#define MODFEM_QTHEAT_VERSION "0.0.0"
#define MODFEM_QTHEAT_MAJOR 0
#define MODFEM_QTHEAT_MINOR 0
#define MODFEM_QTHEAT_MICRO 0

#ifdef MODFEM_QTHEAT_BUILD
  #define MODFEM_QTHEAT_0_0
#endif

#ifndef MODFEM_QTHEAT_0_CURRENT 
  #define MODFEM_QTHEAT_0_CURRENT 0
#endif

#endif
