#ifndef MODFEM_VIEW3D_0_METADATA_HPP
#define MODFEM_VIEW3D_0_METADATA_HPP

// This file has been autogenerated by 'cutehmi.metadata' Qbs module.

#define MODFEM_VIEW3D_NAME "ModFEM.View3d.0"
#define MODFEM_VIEW3D_CUTEHMI_TYPE "extension"
#define MODFEM_VIEW3D_FRIENDLY_NAME "View 3d"
#define MODFEM_VIEW3D_VENDOR "CuteHMI"
#define MODFEM_VIEW3D_DOMAIN "cutehmi.kde.org"
#define MODFEM_VIEW3D_VERSION "0.0.0"
#define MODFEM_VIEW3D_MAJOR 0
#define MODFEM_VIEW3D_MINOR 0
#define MODFEM_VIEW3D_MICRO 0

#ifdef MODFEM_VIEW3D_BUILD
  #define MODFEM_VIEW3D_0_0
#endif

#ifndef MODFEM_VIEW3D_0_CURRENT 
  #define MODFEM_VIEW3D_0_CURRENT 0
#endif

#endif
